# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

resources:
  repositories:
    - repository: template-scripts
      type: github
      name: dmedeiros-veracode/template-scripts
      endpoint: dmedeiros-veracode

trigger: none
pr:
  paths:
    exclude: 
     - templates/*
     - .github/*

pool:
  vmImage: 'windows-latest'

stages:
- stage: Build

  jobs:
  - job: Build_Release
    displayName: Release Build
  
    steps:
    - template: templates/steps/abstract-build-steps.yml
      parameters:
        buildConfiguration: 'Release'

    - task: PublishPipelineArtifact@1
      inputs:
            targetPath: $(Build.StagingDirectory)\WebApp.zip  #$(System.DefaultWorkingDirectory)/bin/WebApp
            artifactName: WebApp_Release

  - job: Build_Debug
    displayName: Debug Build
  
    steps:
    - template: templates/steps/abstract-build-steps.yml
      parameters:
        buildConfiguration: 'Debug'
        
    - task: PublishPipelineArtifact@1
      inputs:
            targetPath: $(Build.StagingDirectory)\WebApp.zip  #$(System.DefaultWorkingDirectory)/bin/WebApp
            artifactName: WebApp_Debug
        
- stage: Testing
  jobs:
  - job: Unit_Testing
    displayName: Unit Testing 

    steps:
    - script: echo Testing
    - script: pwd
    - script: ls -la

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: Security_Testing
  jobs:
  - template: templates/jobs/veracode-sast-pipeline-job.yml@template-scripts
    parameters:
        downloadArtifact: "WebApp_Debug"
