# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
pr:
  paths:
    exclude: 
     - templates/*
     - .github/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build

  jobs:
  - job: Build_Release
    displayName: Release Build
  
    steps:
    - template: templates/steps/release-build-steps.yml
    - script: pwd
    - script: ls -la
    - script: echo $(Build.StagingDirectory)
    - script: ls -la $(Build.StagingDirectory)
    - task: PublishPipelineArtifact@1
      inputs:
            targetPath: $(Build.StagingDirectory)\WebApp.zip  #$(System.DefaultWorkingDirectory)/bin/WebApp
            artifactName: WebApp_Release

  - job: Build_Debug
    displayName: Debug Build
  
    steps:
    - template: templates/steps/debug-build-steps.yml

    #- task: PublishPipelineArtifact@1
    #  inputs:
    #        targetPath: $(Build.StagingDirectory)\WebApp.zip  #$(System.DefaultWorkingDirectory)/bin/WebApp
    #        artifactName: WebApp_Debug
        
- stage: Testing
  jobs:
  - job: 

    steps:
    - script: echo $(System.ArtifactsDirectory)
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'WebApp_Release'
        downloadPath: '$(System.ArtifactsDirectory)'
    - script: pwd
    - script: ls -la
    - script: ls -la $(System.ArtifactsDirectory)



- stage: Security_Testing
  jobs:
  - job:
    steps:
    - script: pwd
    - script: ls -la

  - template: templates/jobs/veracode-sast-pipeline-job.yml
