# File: veracode-sast-platform-job.yml

jobs:       
 - job: SAST_Security_Testing
   displayName: Static Analysis Security Testing

   steps:
   #- task: DownloadPipelineArtifact@2
   #  inputs:
   #     artifact: Debug_WebApp

   - bash: echo 'Veracode Platform SAST'
   - bash: ls -la


   #- task: Veracode@3
   #  inputs:
   #     ConnectionDetailsSelection: 'Endpoint'
   #     AnalysisService: 'Veracode SaaS Connection'
        # apiId: '$(VERACODE_ID)'
        # apiKey: '$(VERACODE_KEY)'
   #     veracodeAppProfile: '$(system.teamProject)'
   #     version: '$(build.buildNumber)'
   #     filepath: '$(Pipeline.Workspace)'  #$(build.artifactstagingdirectory)
   #     sandboxName: 'Development Sandbox'
   #     failBuildIfUploadAndScanBuildStepFails: true
   #     importResults: true
       # failBuildOnPolicyFail: true
       # maximumWaitTime: '360'
